name: Pull Request Validation

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    outputs:
      pipeline: ${{ steps.filter.outputs.pipeline }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Check which files changed
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            pipeline:
              - '.github/workflows/**'

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs:
      - changes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitLint
        run: sudo apt-get install -y gitlint
      - name: Validate Commit Messages
        run: gitlint --commits "origin/main..HEAD"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting with Prettier
        run: pnpm run prettier:check

      - name: Build VuePress
        run: pnpm run build

      - name: Check for broken links
        uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-pr-review
          fail_on_error: true

      - name: Install GitHub action-validator
        uses: asdf-vm/actions/install@v3
        if: ${{ needs.changes.outputs.pipeline == 'true' }}
        with:
          tool_versions: |
            action-validator 0.5.4
      - name: Validate GitHub Actions
        if: ${{ needs.changes.outputs.pipeline == 'true' }}
        run: |
          find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) \
            | xargs -I {} action-validator --verbose {}
